Repository nphuonha2101/library-fe, pull requests merged in 2024-08, with the labels that each got.

#6 write category list product at home
  postcss.config.js
  src/components/layouts/Master.tsx
  src/components/pages/Category/BookItem.tsx
  src/components/pages/Category/BooksContainer.tsx
  src/components/pages/Category/Category.scss
  src/components/pages/Category/CategoryBar.tsx
  src/components/pages/Category/CategoryBarButton.tsx
  src/components/pages/Category/CategoryList.tsx
  src/components/vendors/Buttons/GoTopButton.tsx
  src/hooks/useFetchBooks.ts
  src/interfaces/IBookItem.ts
  src/interfaces/ICategoryProps.ts
  src/routes/index.ts
  tailwind.config.js
Labels: enhancement

#8 Create Header Footer
  index.html
  package-lock.json
  package.json
  src/components/layouts/Master.tsx
  src/components/paritials/Footer/Footer.tsx
  src/components/paritials/Header/Header.tsx
  src/index.css
  src/main.tsx
  tailwind.config.js
Labels: enhancement

#9 Create Login Register
  src/components/pages/Form/Login.tsx
  src/components/pages/Form/Register.tsx
  src/routes/index.ts
Labels: enhancement

#10 5-writing-Cart
  src/components/pages/Cart/Cart.tsx
Labels: enhancement

#20 14-chỉnh-sửa-lại-trang-Cart
  src/components/pages/Cart/Cart.tsx
  src/routes/index.ts
Labels: enhancement

#16 edit page book detail
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/pages/Category/BookDetail.tsx
  src/routes/index.ts
Labels: enhancement

#22 Tạo tính năng book review thành công
  .gitignore
  package-lock.json
  package.json
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/paritials/Header/Header.tsx
  src/components/paritials/Header/SearchModal.tsx
  src/components/paritials/Reviews/ReviewItem.tsx
  src/components/paritials/Reviews/Reviews.tsx
  src/index.css
  src/interfaces/IBookItem.ts
  src/interfaces/IBookReview.ts
  src/interfaces/ILoan.ts
  src/redux/loanSlice.ts
  src/redux/store.ts
  src/routes/index.ts
  src/services/csrfTokenService.ts
  src/utils/dateFormat.ts
Labels: enhancement

#23 #12 - Tạo admin layout
  src/components/layouts/Admin.tsx
  src/components/layouts/Master.tsx
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/pages/Category/BookItem.tsx
  src/components/pages/Category/BooksContainer.tsx
  src/components/pages/Category/CategoryBar.tsx
  src/components/pages/Category/CategoryBarButton.tsx
  src/components/pages/Category/CategoryList.tsx
  src/components/pages/adminPages/BookManagement/BookManagement.tsx
  src/components/paritials/DataTable/DataTable.tsx
  src/interfaces/IApiResult.ts
  src/interfaces/IAuthor.ts
  src/interfaces/IBookItem.ts
  src/interfaces/ICategory.ts
  src/interfaces/ILayout.ts
  src/interfaces/ILoan.ts
  src/interfaces/ILoanDetail.ts
  src/interfaces/ILoanFine.ts
  src/interfaces/IRoute.ts
  src/interfaces/IUser.ts
  src/routes/index.ts
Labels: enhancement

#26 Update branch
  src/components/layouts/Admin.tsx
  src/components/layouts/Master.tsx
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/pages/Category/BookItem.tsx
  src/components/pages/Category/BooksContainer.tsx
  src/components/pages/Category/CategoryBar.tsx
  src/components/pages/Category/CategoryBarButton.tsx
  src/components/pages/Category/CategoryList.tsx
  src/components/pages/adminPages/BookManagement/BookManagement.tsx
  src/components/paritials/DataTable/DataTable.tsx
  src/interfaces/IApiResult.ts
  src/interfaces/IAuthor.ts
  src/interfaces/IBookItem.ts
  src/interfaces/ICategory.ts
  src/interfaces/ILayout.ts
  src/interfaces/ILoan.ts
  src/interfaces/ILoanDetail.ts
  src/interfaces/ILoanFine.ts
  src/interfaces/IRoute.ts
  src/interfaces/IUser.ts
  src/routes/index.ts
Labels: wontfix

#27 Hotfix: Fix UI
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/pages/Form/Login.tsx
  src/components/paritials/Header/Header.tsx
  src/components/paritials/Header/SearchModal.tsx
  src/components/paritials/Reviews/ReviewItem.tsx
  src/components/paritials/Reviews/Reviews.tsx
  src/components/vendors/Buttons/GoTopButton.tsx
Labels: bug

#29 handle login, register, logout
  src/components/pages/Form/Login.tsx
  src/components/pages/Form/Register.tsx
  src/components/paritials/Header/Header.tsx
  src/routes/index.ts
  src/utils/localStorageUtil.ts
Labels: enhancement

#32 handle get info user and role when login
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/paritials/Header/Header.tsx
  src/components/paritials/Reviews/ReviewItem.tsx
  src/components/paritials/Reviews/Reviews.tsx
Labels: enhancement

#31 28-create-about-page
  src/components/pages/About/About.tsx
  src/routes/index.ts
Labels: enhancement

#34 Update branch
  package-lock.json
  package.json
  src/App.tsx
  src/components/pages/About/About.tsx
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/pages/Cart/Cart.tsx
  src/components/pages/Cart/LoanCart.tsx
  src/components/pages/Category/BookItem.tsx
  src/components/pages/Category/BooksContainer.tsx
  src/components/pages/Form/Login.tsx
  src/components/pages/Form/Register.tsx
  src/components/pages/LoanHistory/LoanHistory.tsx
  src/components/paritials/Header/Header.tsx
  src/components/paritials/Reviews/ReviewItem.tsx
  src/components/paritials/Reviews/Reviews.tsx
  src/interfaces/IBookItem.ts
  src/interfaces/ILoan.ts
  src/interfaces/ILoanDetail.ts
  src/redux/loanSlice.ts
  src/redux/rootReducer.ts
  src/redux/store.ts
  src/routes/index.ts
  src/utils/dateFormat.ts
Labels: enhancement

#35 28-create-about-page
  src/components/pages/About/About.tsx
Labels: enhancement

#36 #18 - Tích hợp TinyMCE Editor
  package-lock.json
  package.json
  src/App.tsx
  src/components/layouts/Admin.tsx
  src/components/pages/BookDetail/BookDetail.tsx
  src/components/pages/Cart/LoanCart.tsx
  src/components/pages/Form/Login.tsx
  src/components/pages/Home/Home.tsx
  src/components/pages/LoanHistory/LoanHistory.tsx
  src/components/pages/adminPages/BookManagement/BookManagement.tsx
  src/components/paritials/DataTable/DataTable.tsx
  src/components/paritials/Header/Header.tsx
  src/components/paritials/Reviews/Reviews.tsx
  src/components/paritials/SlateEditor/SlateEditor.tsx
  src/components/paritials/SlateEditor/Toolbar.tsx
  src/components/paritials/TinyMCEEditor/TinyMceEditor.tsx
  src/interfaces/CustomElement.ts
  src/interfaces/CustomText.ts
  src/interfaces/IRoute.ts
  src/redux/loanSlice.ts
  src/routes/index.ts
  src/services/csrfTokenService.ts
Labels: enhancement
